"""Temel Kriptografi — modül sonu testleri (anlama odaklı sorular)."""

from __future__ import annotations

# section_id -> 10 soru (opts sırası A, B, C, D)
QUESTIONS: dict[str, list[dict]] = {
    "kr-m1-l09": [
        {
            "q": "Bir saldırgan ağda HTTPS trafiğini okuyamıyor; ancak indirilen kurulum dosyasının baytlarını değiştirip dağıtıyor. En kritik eksik güvenlik hedefi hangisidir?",
            "opts": [
                "Gizlilik — içerik zaten şifreli aktarılıyor",
                "Bütünlük — dosyanın değiştirilmediği doğrulanmıyor",
                "İnkâr edememe — kim gönderdi bilinmiyor",
                "Erişilebilirlik — hizmet kapalı",
            ],
            "correct": "B",
            "rationale": "Şifreleme okumayı engeller; paket veya dosya değişikliğini tespit etmek bütünlük (hash, imza, MAC) gerektirir.",
        },
        {
            "q": "CyberChef’te «SGVsbG8=» çıktısını görüyorsunuz; metin okunaklı hale geliyor ama anahtar kullanılmadı. Bu çıktı en uygun nasıl sınıflanır?",
            "opts": [
                "AES ile şifrelenmiş ciphertext",
                "Base64 encoding — gizlilik sağlamaz",
                "SHA-256 hash değeri",
                "TLS oturum anahtarı",
            ],
            "correct": "B",
            "rationale": "Encoding format dönüşümüdür; tersine çevrilebilir ve gizlilik veya bütünlük garantisi vermez.",
        },
        {
            "q": "Modern kriptografide güvenlik varsayımı olarak hangisi doğrudur kabul edilir?",
            "opts": [
                "Algoritma tasarımı tamamen gizli tutulmalıdır",
                "Güvenlik, anahtarın gizli ve doğru yönetilmesine dayanır (Kerckhoffs)",
                "Şifreleme tek başına kimlik doğrulamayı da sağlar",
                "Uzun anahtar her zaman yeterlidir; mod önemli değildir",
            ],
            "correct": "B",
            "rationale": "Kerckhoffs ilkesine göre sistem güvenliği anahtar gizliliğine dayanır; algoritma bilinebilir.",
        },
        {
            "q": "Aynı parola için her girişte farklı 60 karakterlik çıktı üreten bir sistemde (ör. bcrypt) bu çıktılar en doğru ne olarak adlandırılır?",
            "opts": [
                "Simetrik şifreli metin (ciphertext)",
                "Tek yönlü parola hash çıktısı (salt ile)",
                "X.509 sertifikası",
                "Base64 encoded parola",
            ],
            "correct": "B",
            "rationale": "Parola saklama için hash + salt kullanılır; geri çözme değil doğrulama amaçlıdır.",
        },
        {
            "q": "İki taraf arasında şifreli kanal kuruldu; fakat istemci aslında saldırganın sunucusuna bağlanmış. Hangi risk gerçekleşmiş olabilir?",
            "opts": [
                "Yalnızca gizlilik ihlali",
                "Kimlik doğrulama eksikliği — yanlış taraf ile güvenli kanal",
                "Hash çakışması",
                "ECB modu tekrar deseni",
            ],
            "correct": "B",
            "rationale": "Şifreli kanal, doğru taraf doğrulanmadan MITM senaryosunda yanıltıcı olabilir.",
        },
        {
            "q": "TLS 1.3 el sıkışması pratikte hangi ihtiyacı bir arada hedefler?",
            "opts": [
                "Yalnızca dosya sıkıştırma",
                "Oturum anahtarı üretimi ve (en azından sunucu) kimlik doğrulama",
                "Parolaları veritabanında düz metin saklama",
                "OTP anahtarını e-posta ile gönderme",
            ],
            "correct": "B",
            "rationale": "TLS protokolü anahtar anlaşması ile sertifika zinciri üzerinden kimlik doğrulamayı birleştirir.",
        },
        {
            "q": "Bir sözleşmenin «kim tarafından imzalandığı» teknik olarak ispatlanmak isteniyor. Hangi mekanizma doğrudan bu role uygundur?",
            "opts": [
                "MD5 hash karşılaştırması (tek başına)",
                "Özel anahtarla dijital imza",
                "Base64 encoding",
                "Sezar şifresi",
            ],
            "correct": "B",
            "rationale": "Dijital imza, mesajın belirli bir özel anahtar sahibiyle ilişkilendirilmesini sağlar.",
        },
        {
            "q": "«Bu kullanıcı admin paneline girebilir mi?» sorusu hangi kavrama aittir?",
            "opts": [
                "Kimlik doğrulama (authentication)",
                "Yetkilendirme (authorization)",
                "Gizlilik (confidentiality)",
                "Frekans analizi",
            ],
            "correct": "B",
            "rationale": "Kimlik doğrulama «kim?»; yetkilendirme «neye erişebilir?» sorusunu yanıtlar.",
        },
        {
            "q": "AEAD (ör. AES-GCM) kullanımının simetrik şifrelemeden ek beklentisi nedir?",
            "opts": [
                "Anahtarın herkese açık paylaşılması",
                "Şifreleme ile birlikte bütünlük/doğrulama etiketi",
                "Hash’in geri çevrilebilir olması",
                "IV’nin her zaman sabit kalması",
            ],
            "correct": "B",
            "rationale": "AEAD hem gizlilik hem de ciphertext’in değiştirilmediğini doğrular.",
        },
        {
            "q": "«JWT’yi Base64 decode edince payload okunuyor, o halde güvende» yorumu neden yanlıştır?",
            "opts": [
                "JWT hiç veri taşımaz",
                "Okunabilirlik gizlilik değildir; imza/anahtar doğrulaması ayrı konudur",
                "JWT yalnızca TLS içinde kullanılamaz",
                "Decode işlemi her zaman şifre çözmektir",
            ],
            "correct": "B",
            "rationale": "JWT payload sıklıkla sadece encoded’dır; güven imza/HMAC ve anahtar yönetimine bağlıdır.",
        },
    ],
    "kr-m2-l09": [
        {
            "q": "0x41 değeri ASCII’de hangi karaktere karşılık gelir?",
            "opts": ["'A'", "'0'", "Satır sonu (LF)", "Boşluk"],
            "correct": "A",
            "rationale": "0x41 = 65 onluk = Latin büyük harf A.",
        },
        {
            "q": "A ⊕ B = 0 ve A ⊕ C = 0 ise B ve C için ne söylenebilir?",
            "opts": [
                "B ve C aynıdır (XOR ile C’den A elde edilir)",
                "B ve C her zaman farklıdır",
                "XOR geri döndürülemez",
                "Sonuç her zaman 0xFF’tir",
            ],
            "correct": "A",
            "rationale": "XOR özyinelemelidir; aynı değerle XOR sıfır üretir.",
        },
        {
            "q": "OTP’de aynı anahtar iki farklı mesajda tekrar kullanılırsa saldırgan hangi bilgiyi elde edebilir?",
            "opts": [
                "Doğrudan düz metin anahtarı",
                "C1 ⊕ C2 = P1 ⊕ P2 ilişkisi",
                "Sertifika zincirini",
                "RSA özel anahtarını",
            ],
            "correct": "B",
            "rationale": "Anahtar tekrarında ciphertext’lerin XOR’u anahtarsız düz metin XOR’una indirgenir.",
        },
        {
            "q": "8 bitlik rastgele bir anahtar için teorik anahtar uzayı kaçtır?",
            "opts": ["8", "16", "256", "65536"],
            "correct": "C",
            "rationale": "2^8 = 256 olası anahtar.",
        },
        {
            "q": "Parola türetme, IV veya nonce için hangi tür rastgelelik gerekir?",
            "opts": [
                "Dil random() fonksiyonu yeterli",
                "Kriptografik olarak güvenli rastgele sayı üreteci (CSPRNG)",
                "Sistem saatine göre artan sayaç yeterli",
                "Kullanıcı adının hash’i",
            ],
            "correct": "B",
            "rationale": "Tahmin edilebilir rastgelelik IV/nonce tekrarı ve anahtar tahminine yol açar.",
        },
        {
            "q": "«Bu çıktı her çalıştırmada aynı uzunlukta ve aynı girdi için aynı» ise en olası kategorisi nedir?",
            "opts": [
                "GCM ile şifreleme (nonce değişir)",
                "Deterministik hash fonksiyonu",
                "RSA şifreleme",
                "One-time pad",
            ],
            "correct": "B",
            "rationale": "Hash aynı girdi için sabit uzunlukta deterministik çıktı verir.",
        },
        {
            "q": "128 bitlik bir anahtar için brute force «her anahtarı dene» uzayı kabaca ne kadardır?",
            "opts": ["128", "2^128", "128!", "10^128 byte"],
            "correct": "B",
            "rationale": "n bit anahtar için 2^n olasılık.",
        },
        {
            "q": "Aynı düz metin iki kez AES-GCM ile şifrelendiğinde ciphertext’in farklı olması için genelde ne gerekir?",
            "opts": [
                "Aynı IV/nonce’un bilinçli tekrarı",
                "Her şifrelemede benzersiz nonce/IV",
                "ECB modu",
                "Anahtarsız şifreleme",
            ],
            "correct": "B",
            "rationale": "Rastgele nonce/IV aynı plaintext’te farklı ciphertext üretir.",
        },
        {
            "q": "Hex «4a4b2c» dizisini yanlışlıkla ASCII metin sanmak hangi hataya örnektir?",
            "opts": [
                "Encoding ile şifrelemeyi karıştırmak",
                "Sertifika süresini kontrol etmemek",
                "TLS’i kapatmak",
                "Salt kullanmak",
            ],
            "correct": "A",
            "rationale": "Hex yalnızca gösterim biçimidir; gizlilik sağlamaz.",
        },
        {
            "q": "Simetrik ve asimetrik şifrelemenin temel farkı hangisidir?",
            "opts": [
                "Simetrikte tek paylaşılan gizli anahtar; asimetrikte public/private çifti",
                "Asimetrik her zaman daha hızlıdır",
                "Simetrik yalnızca hash üretir",
                "Asimetrikte anahtar gerekmez",
            ],
            "correct": "A",
            "rationale": "Anahtar dağıtım modeli iki ailenin ayırt edici özelliğidir.",
        },
    ],
    "kr-m3-l09": [
        {
            "q": "Tek alfabeli İngilizce metinde Sezar şifresine karşı en etkili klasik saldırı hangisidir?",
            "opts": [
                "Man-in-the-middle",
                "Frekans analizi / 25 kaydırma denemesi",
                "Rainbow table",
                "Padding oracle",
            ],
            "correct": "B",
            "rationale": "Küçük anahtar uzayı ve dil istatistikleri Sezar’ı kırılabilir kılar.",
        },
        {
            "q": "OTP’nin teorik mükemmel gizliliği pratikte hangi koşul bozulunca çöker?",
            "opts": [
                "Anahtarın bir kez kullanılıp atılması",
                "Aynı anahtar parçasının iki mesajda tekrar kullanılması",
                "Anahtarın mesajdan uzun olması",
                "Gerçek rastgele anahtar üretimi",
            ],
            "correct": "B",
            "rationale": "Anahtar tekrarı OTP’yi stream cipher XOR saldırısına indirger.",
        },
        {
            "q": "Vigenère’ye karşı Kasiski ve frekans yöntemleri hangi zayıflığı hedefler?",
            "opts": [
                "Anahtar uzunluğunun tahmini ve periyodik örüntü",
                "RSA modülünün çarpanlarına ayrılması",
                "TLS sertifika süresi",
                "Argon2 bellek maliyeti",
            ],
            "correct": "A",
            "rationale": "Tekrarlayan anahtar blokları periyodu ele verir.",
        },
        {
            "q": "Klasik şifrelerin modern standartlara göre ortak sorunu nedir?",
            "opts": [
                "Çok büyük anahtar uzayı",
                "Küçük anahtar uzayı ve yapısal istatistik sızıntısı",
                "AEAD zorunluluğu",
                "Quantum direnci",
            ],
            "correct": "B",
            "rationale": "Klasik yöntemler bilgisayar öncesi tehdit modeline göre tasarlanmıştır.",
        },
        {
            "q": "Transposition (ör. rail fence) saldırısı genelde neyi bozar?",
            "opts": [
                "Harf sırasını değiştirir; frekans dağılımı korunabilir",
                "Her harfi rastgele harfle değiştirir",
                "Anahtarı herkese açık yapar",
                "Hash çakışması üretir",
            ],
            "correct": "A",
            "rationale": "Yer değiştirme harf frekansını koruyabilir; yapısal analiz mümkündür.",
        },
        {
            "q": "Kerckhoffs ilkesi klasik/modern bağlamda ne ister?",
            "opts": [
                "Sadece şifreli metin gizli kalsın",
                "Sistem güvenliği anahtar gizliliğine dayansın; yöntem bilinebilir olsun",
                "Algoritma asla yayınlanmasın",
                "Anahtar herkese açık olsun",
            ],
            "correct": "B",
            "rationale": "Güvenlik anahtara dayanır; gizli algoritma sürdürülebilir değildir.",
        },
        {
            "q": "Caesar şifresinde 26 harfli alfabede kaç anlamlı kaydırma vardır (0 hariç)?",
            "opts": ["1", "13", "25", "256"],
            "correct": "C",
            "rationale": "Kaydırma 1–25 arası; brute force dakikalar içinde biter.",
        },
        {
            "q": "Klasik şifre çıktısını üretimde güvenlik için kullanmak neden reddedilir?",
            "opts": [
                "Çok yavaş oldukları için",
                "Bilinen kriptanalizle pratikte kırılabilir oldukları için",
                "TLS ile uyumsuz oldukları için",
                "Yalnızca görsel içerikte çalıştıkları için",
            ],
            "correct": "B",
            "rationale": "Eğitim amaçlıdır; gerçek gizlilik sağlamazlar.",
        },
        {
            "q": "Kriptografi ile kriptanaliz ilişkisi en doğru nasıldır?",
            "opts": [
                "Kriptanaliz şifre tasarımını test eden saldırı bilimidir",
                "Aynı şeydir",
                "Kriptanaliz yalnızca hukuki terimdir",
                "Kriptanaliz hash üretir",
            ],
            "correct": "A",
            "rationale": "Tasarım ve saldırı birlikte güvenliği olgunlaştırır.",
        },
        {
            "q": "Modern blok şifrelerde «anahtar uzunluğu» artırmanın amacı nedir?",
            "opts": [
                "Brute force maliyetini artırmak",
                "Base64 çıktısını kısaltmak",
                "Sertifika süresini uzatmak",
                "Encoding’i şifrelemek",
            ],
            "correct": "A",
            "rationale": "Uzun anahtar arama uzayını büyütür; mod ve protokol ayrıca önemlidir.",
        },
    ],
    "kr-m4-l09": [
        {
            "q": "Aynı 16 baytlık plaintext bloğu ECB modunda iki kez şifrelendiğinde ciphertext’te ne görülür?",
            "opts": [
                "İki farklı rastgele blok",
                "İki özdeş şifreli blok — tekrar sızar",
                "Hiç şifrelenmez",
                "Yalnızca IV değişir",
            ],
            "correct": "B",
            "rationale": "ECB blokları bağımsız şifreler; eşit plaintext = eşit ciphertext.",
        },
        {
            "q": "CBC modunda IV’nin görevi nedir?",
            "opts": [
                "Aynı ilk blokta bile farklı ciphertext başlatmak",
                "Parolayı hashlemek",
                "Sertifika imzalamak",
                "Anahtarı herkese dağıtmak",
            ],
            "correct": "A",
            "rationale": "IV/chaining tekrar eden desenleri gizlemeye yardım eder; IV benzersiz olmalıdır.",
        },
        {
            "q": "Üretimde neden «AES-ECB ile dosya şifrele» önerilmez?",
            "opts": [
                "ECB görüntü ve yapı tekrarlarını gizlemez",
                "ECB quantum dirençlidir",
                "ECB yalnızca asimetrik çalışır",
                "ECB parola hash’idir",
            ],
            "correct": "A",
            "rationale": "ECB blok bağımsızlığı bilinen ciddi zayıflıktır.",
        },
        {
            "q": "AES-GCM kullanırken şifre çözmeden önce ne yapılmalıdır?",
            "opts": [
                "Authentication tag doğrulanmalı",
                "IV her zaman sıfır olmalı",
                "Anahtar log dosyasına yazılmalı",
                "Padding oracle istenmeli",
            ],
            "correct": "A",
            "rationale": "AEAD’de tag doğrulanmadan plaintext güvenilir sayılmaz.",
        },
        {
            "q": "128 bit AES anahtarı ile 256 bit arasındaki fark pratikte nedir?",
            "opts": [
                "Brute force zorluğu (uzay boyutu)",
                "GCM tag uzunluğu",
                "X.509 formatı",
                "Base64 satır uzunluğu",
            ],
            "correct": "A",
            "rationale": "Anahtar uzunluğu arama uzayını belirler; mod/protokol ayrı seçilir.",
        },
        {
            "q": "Stream cipher ile block cipher farkı hangisidir?",
            "opts": [
                "Stream genelde bit/byte akışı; block sabit boyutlu bloklar",
                "Stream yalnızca hash üretir",
                "Block şifre anahtar gerektirmez",
                "Stream sadece klasik şifredir",
            ],
            "correct": "A",
            "rationale": "ChaCha20 stream; AES tipik blok şifresidir.",
        },
        {
            "q": "3DES’in modern sistemlerde terk edilmesinin ana nedeni?",
            "opts": [
                "Küçük etkin anahtar ve performans / güvenlik endişeleri",
                "TLS ile uyumsuzluğu",
                "Yalnızca görüntü şifreleyememesi",
                "Hash fonksiyonu olması",
            ],
            "correct": "A",
            "rationale": "3DES legacy; AES ve ChaCha20 tercih edilir.",
        },
        {
            "q": "ChaCha20-Poly1305 paketi ne sunar?",
            "opts": [
                "Stream şifreleme + Poly1305 ile bütünlük (AEAD benzeri paket)",
                "Yalnızca Base64",
                "RSA anahtar üretimi",
                "DNS kaydı imzalama",
            ],
            "correct": "A",
            "rationale": "Modern TLS ve libsodium’da yaygın AEAD alternatifidir.",
        },
        {
            "q": "Padding oracle saldırısı hangi bağlamla ilişkilidir?",
            "opts": [
                "Yanlış uygulanan CBC padding doğrulaması ve hata sızıntısı",
                "OTP anahtar tekrarı",
                "Sezar kaydırması",
                "MD5 collision",
            ],
            "correct": "A",
            "rationale": "Uygulama katmanı hata mesajları anahtar veya plaintext sızdırabilir.",
        },
        {
            "q": "Dosya şifrelemede «rastgele nonce + AEAD mod» seçmenin gerekçesi?",
            "opts": [
                "Tekrar ve manipülasyona karşı gizlilik + bütünlük",
                "Daha kısa anahtar kullanmak",
                "Sertifikasız HTTPS",
                "Deterministik ciphertext istemek",
            ],
            "correct": "A",
            "rationale": "GCM/ChaCha20-Poly1305 üretimde standart tercihtir.",
        },
    ],
    "kr-m5-l09": [
        {
            "q": "SHA-256 çıktısı değiştirilen bir dosya için tekrar hesaplanırsa ne olur?",
            "opts": [
                "Aynı hash kalır",
                "Farklı hash — küçük değişim bile avalanche ile değiştirir",
                "Hash geri çözülür",
                "Hash anahtar üretir",
            ],
            "correct": "B",
            "rationale": "Hash tek yönlüdür; bütünlük kontrolü için kullanılır.",
        },
        {
            "q": "HMAC’in düz SHA-256 hash’ten farkı nedir?",
            "opts": [
                "Gizli anahtarla bütünlük; saldırgan hash’i tek başına yeniden üretemez",
                "Daha kısa çıktı",
                "Her zaman şifreleme yapar",
                "Parolayı düz metne çevirir",
            ],
            "correct": "A",
            "rationale": "HMAC keyed integrity sağlar; paylaşılan sır gerekir.",
        },
        {
            "q": "Parola veritabanında neden salt kullanılır?",
            "opts": [
                "Aynı parolaların aynı hash’ini ve rainbow table’ı zorlaştırmak",
                "Parolayı şifrelemek",
                "TLS sürümünü artırmak",
                "IV’yi gereksiz kılmak",
            ],
            "correct": "A",
            "rationale": "Salt + yavaş KDF (Argon2id, bcrypt) standarttır.",
        },
        {
            "q": "Argon2id veya PBKDF2’nin amacı nedir?",
            "opts": [
                "Parola türetmede brute force maliyetini artırmak",
                "Ağ paketini şifrelemek",
                "X.509 imzalamak",
                "Frekans analizi",
            ],
            "correct": "A",
            "rationale": "KDF kasıtlı yavaş/bellek maliyetli türetme sağlar.",
        },
        {
            "q": "İki farklı girdinin aynı hash’i üretmesi ne olarak adlandırılır?",
            "opts": ["Collision", "Nonce reuse", "Downgrade", "Padding"],
            "correct": "A",
            "rationale": "Çakışma hash fonksiyonları için tasarım hedefidir.",
        },
        {
            "q": "İndirilen yazılımın SHA-256 değeri resmi sitede yayımlanmış; dosyayı doğruluyorsunuz. Bu kontrol öncelikle hangi hedefe hizmet eder?",
            "opts": ["Gizlilik", "Bütünlük", "İnkâr edememe", "Anonimlik"],
            "correct": "B",
            "rationale": "Hash karşılaştırması değişiklik tespiti içindir; kaynak güveni ayrı konudur.",
        },
        {
            "q": "MAC ile dijital imza arasındaki temel fark?",
            "opts": [
                "MAC paylaşılan gizli anahtar; imza genelde asimetrik ve herkese doğrulanabilir",
                "MAC her zaman daha zayıftır",
                "İmza hash değildir",
                "MAC yalnızca TLS’te yoktur",
            ],
            "correct": "A",
            "rationale": "Kim doğrulayabilir ve anahtar modeli farklıdır.",
        },
        {
            "q": "MD5’i parola veya bütünlük için kullanmak neden reddedilir?",
            "opts": [
                "Bilinen collision ve zayıf güvenlik marjı",
                "Çok yavaş olduğu için",
                "128 bit çıktı verdiği için",
                "Açık kaynak olmadığı için",
            ],
            "correct": "A",
            "rationale": "MD5/SHA-1 legacy; SHA-256+ veya SHA-3 tercih edilir.",
        },
        {
            "q": "Length extension saldırısı hangi aileyle ilişkilidir?",
            "opts": [
                "Merkle-Damgård yapılı hash’ler (ör. MD5, SHA-1) — HMAC ile mitigasyon",
                "RSA padding",
                "OTP",
                "Base64",
            ],
            "correct": "A",
            "rationale": "HMAC veya modern hash tasarımı bu riski hedefler.",
        },
        {
            "q": "«Hash’leyerek şifreledik» ifadesi neden tehlikelidir?",
            "opts": [
                "Hash geri çevrilemez; gizlilik için şifreleme gerekir",
                "Hash her zaman daha güvenlidir",
                "Hash anahtar dağıtır",
                "Hash TLS’i kapatır",
            ],
            "correct": "A",
            "rationale": "Hash ≠ encryption; farklı güvenlik hedefleri.",
        },
    ],
    "kr-m6-l09": [
        {
            "q": "RSA’da herkese açık anahtarın yayınlanmasının amacı nedir?",
            "opts": [
                "Herkesin aynı gizli anahtarı bilmesi",
                "Herkesin şifreleyebilmesi / imzayı doğrulayabilmesi; çözme özel anahtarda",
                "Anahtarın gizli kalması",
                "Hash üretmek",
            ],
            "correct": "B",
            "rationale": "Asimetrik modelde public encrypt/verify, private decrypt/sign.",
        },
        {
            "q": "ECC’nin RSA’ya göre yaygın avantajı hangisidir?",
            "opts": [
                "Daha kısa anahtarla benzer güvenlik seviyesi (daha az kaynak)",
                "Anahtar gerektirmez",
                "Her zaman post-quantum’dur",
                "Yalnızca hash üretir",
            ],
            "correct": "A",
            "rationale": "256-bit ECC ~ 3072-bit RSA güvenlik seviyesi civarı düşünülür.",
        },
        {
            "q": "Diffie-Hellman anahtar değişiminin sağladığı özellik?",
            "opts": [
                "İki tarafın aynı oturum sırrını açık kanaldan paylaşmadan üretmesi",
                "Parolayı hashlemesi",
                "Sertifikasız HTTPS",
                "OTP anahtar tekrarı",
            ],
            "correct": "A",
            "rationale": "KDE protokollerin temelidir; kimlik doğrulama ayrıca gerekir.",
        },
        {
            "q": "Forward secrecy (PFS) ne anlama gelir?",
            "opts": [
                "Uzun vadeli özel anahtar sızsa bile geçmiş oturum anahtarlarının korunması",
                "Sertifikanın süresiz geçerli olması",
                "ECB kullanımı",
                "Salt’sız parola",
            ],
            "correct": "A",
            "rationale": "Ephemeral DH (TLS 1.3) geçmiş trafiği korur.",
        },
        {
            "q": "OAEP padding RSA şifrelemede neye karşı yardımcı olur?",
            "opts": [
                "Deterministik şifreleme ve bazı metin saldırıları",
                "Frekans analizi",
                "DNS spoofing",
                "Wi-Fi kanal çakışması",
            ],
            "correct": "A",
            "rationale": "Padding şema güvenliğinin parçasıdır; doğru API şart.",
        },
        {
            "q": "X.509 sertifikası pratikte ne bağlar?",
            "opts": [
                "Genel anahtar ile kimlik (alan adı, kuruluş) — CA imzasıyla",
                "Parolayı düz metne",
                "OTP anahtarını",
                "Base64 çıktısını",
            ],
            "correct": "A",
            "rationale": "PKI kimlik bağlama ve zincir doğrulaması sağlar.",
        },
        {
            "q": "«Özel anahtarı e-posta ile gönderdim» hangi hatayı gösterir?",
            "opts": [
                "Anahtar dağıtımının güvensiz kanaldan yapılması",
                "ECC kullanımı",
                "HMAC kullanımı",
                "Salt kullanımı",
            ],
            "correct": "A",
            "rationale": "Private key asla açık kanalda taşınmamalıdır.",
        },
        {
            "q": "2048 bit RSA anahtarı bugün için genel öneri açısından?",
            "opts": [
                "Birçok profilde minimum kabul; 3072+ uzun ömür için düşünülür",
                "Her zaman yetersiz — 512 bit yeterli",
                "Sadece hash için",
                "TLS ile kullanılamaz",
            ],
            "correct": "A",
            "rationale": "Organizasyon politikasına göre güncellenir; ECC alternatiftir.",
        },
        {
            "q": "Dijital imza doğrulaması başarılı — bu ne ispatlar?",
            "opts": [
                "İmzayı üreten özel anahtar sahibi mesajla ilişkilidir (politika ve sertifika bağlamında)",
                "Mesajın gizli olduğu",
                "Parolanın güçlü olduğu",
                "ECB’nin güvenli olduğu",
            ],
            "correct": "A",
            "rationale": "İmza bütünlük ve kaynak bağlama sağlar; gizlilik ayrı.",
        },
        {
            "q": "PKI’de ara sertifika (intermediate CA) rolü?",
            "opts": [
                "Kök CA’yı izole edip günlük sertifika üretimini ölçeklendirmek",
                "Parolayı şifrelemek",
                "Wireshark filtresi",
                "OTP üretmek",
            ],
            "correct": "A",
            "rationale": "Zincir: leaf → intermediate → root.",
        },
    ],
    "kr-m7-l09": [
        {
            "q": "Tarayıcı «bağlantınız güvenli değil» uyarısı veriyor; sertifika adı alan adıyla uyuşmuyor. Sorun en çok nedir?",
            "opts": [
                "Hostname / SAN uyumsuzluğu veya yanlış sertifika",
                "AES-GCM nonce tekrarı",
                "Argon2 parametresi",
                "Base64 padding",
            ],
            "correct": "A",
            "rationale": "Kimlik doğrulama sertifika-alan adı eşleşmesine bağlıdır.",
        },
        {
            "q": "TLS el sıkışmasının temel çıktısı nedir?",
            "opts": [
                "Ortak oturum anahtarı ve üzerinde şifreli kayıt protokolü",
                "Parola hash dosyası",
                "OTP anahtar defteri",
                "ECB görüntü",
            ],
            "correct": "A",
            "rationale": "Handshake KDE + kimlik doğrulama; sonra application data.",
        },
        {
            "q": "Certificate pinning ne riski azaltır?",
            "opts": [
                "Yetkisiz veya sahte CA ile imzalanmış ara sertifika kullanımı (MITM)",
                "Parola brute force",
                "Sezar şifresi",
                "Rainbow table",
            ],
            "correct": "A",
            "rationale": "Beklenen public key/sertifika ile sabitlenir.",
        },
        {
            "q": "CRL ve OCSP ne için kullanılır?",
            "opts": [
                "İptal edilmiş (revoke) sertifikaları kontrol",
                "Parola türetme",
                "DNS kaydı şifreleme",
                "Wi-Fi şifresi",
            ],
            "correct": "A",
            "rationale": "Revocation kontrolü PKI güveninin parçasıdır.",
        },
        {
            "q": "Self-signed sertifika üretim ortamında neden sorunlu?",
            "opts": [
                "Genel güvenilen CA zinciri yok; MITM ve yanlış güven kolaylaşır",
                "Her zaman daha hızlıdır",
                "TLS 1.3 desteklemez",
                "Hash üretemez",
            ],
            "correct": "A",
            "rationale": "İç PKI veya public CA ile yönetilmeli; istisna bilinçli olmalı.",
        },
        {
            "q": "mTLS’te istemci sertifikası eklenmesinin amacı?",
            "opts": [
                "Sunucunun da istemciyi kimlik doğrulaması",
                "ECB modunu zorunlu kılmak",
                "HTTP’yi hızlandırmak",
                "Salt kaldırmak",
            ],
            "correct": "A",
            "rationale": "Karşılıklı kimlik doğrulama API/mikroservislerde görülür.",
        },
        {
            "q": "Cipher suite seçiminde «AES_128_GCM» parçası ne ifade eder?",
            "opts": [
                "Simetrik algoritma, anahtar uzunluğu ve mod (GCM) kombinasyonu",
                "Hash algoritması",
                "CA adı",
                "DNS TTL",
            ],
            "correct": "A",
            "rationale": "Suite algoritma paketini tanımlar; zayıf suite’ler kapatılmalı.",
        },
        {
            "q": "HSTS başlığının kullanıcıya faydası?",
            "opts": [
                "Tarayıcıyı mümkün olduğunca HTTPS kullanmaya zorlar — sslstrip riskini azaltır",
                "Parolayı hashler",
                "OTP üretir",
                "Sertifikayı imzalar",
            ],
            "correct": "A",
            "rationale": "İlk bağlantı hariç downgrade saldırılarını sınırlar.",
        },
        {
            "q": "HTTPS olmadan login formu göndermek hangi tehdidi artırır?",
            "opts": [
                "Oturum çerezi ve kimlik bilgilerinin ağda okunması (gizlilik ihlali)",
                "Hash collision",
                "OTP mükemmelliği",
                "ECB deseni",
            ],
            "correct": "A",
            "rationale": "TLS gizlilik ve bütünlük sağlar; form tek başına şifrelemez.",
        },
        {
            "q": "Sertifika zinciri doğrulaması başarısız — kullanıcı ne yapmalı (genel öneri)?",
            "opts": [
                "Uyarıyı yok sayıp devam etmemek; nedeni araştırmak veya IT’ye bildirmek",
                "Her zaman «ileri» de",
                "Sertifikayı silmek",
                "TLS’i kapatmak",
            ],
            "correct": "A",
            "rationale": "Zincir kırığı MITM veya yanlış yapılandırma işaretidir.",
        },
    ],
    "kr-m8-l05": [
        {
            "q": "Kodda `AES/ECB/PKCS5Padding` ile kredi kartı alanı şifrelemek?",
            "opts": [
                "Kabul edilebilir modern pratik",
                "Reddedilmeli — ECB tekrar ve yapı sızıntısı riski",
                "Yalnızca hash için",
                "TLS yerine yeterli",
            ],
            "correct": "B",
            "rationale": "ECB üretim verisi için uygun değildir; AEAD tercih edilir.",
        },
        {
            "q": "Kaynak kodunda `const API_KEY = \"sk-live-...\"` bulunması?",
            "opts": [
                "Hardcoded secret — derhal rotasyon ve gizli depolama gerekir",
                "Kerckhoffs ihlali değildir",
                "Salt alternatifidir",
                "HSTS alternatifidir",
            ],
            "correct": "A",
            "rationale": "Anahtarlar kodda veya repoda tutulmamalıdır.",
        },
        {
            "q": "Aynı AES-GCM anahtarıyla aynı nonce iki kez kullanılırsa?",
            "opts": [
                "Güvenlik ciddi şekilde kırılabilir (keystream XOR)",
                "Performans artar",
                "Hash collision olur",
                "Sertifika yenilenir",
            ],
            "correct": "A",
            "rationale": "Nonce tekrarı GCM için felaket senaryosudur.",
        },
        {
            "q": "«Kendi şifreleme protokolümüzü yazdık, AES kullanıyoruz» ifadesindeki asıl risk?",
            "opts": [
                "Roll-your-own protokol; inceleme ve standart şema eksikliği",
                "AES’in yavaş olması",
                "Base64 kullanımı",
                "Wireshark",
            ],
            "correct": "A",
            "rationale": "Hazır TLS/libsodium gibi denenmiş yapılar tercih edilir.",
        },
        {
            "q": "libsodium / cryptography (high-level API) tercihinin gerekçesi?",
            "opts": [
                "Güvenli varsayılanlar ve yanlış mod kombinasyonunu azaltma",
                "Daha zayıf şifreleme",
                "ECB zorunluluğu",
                "Anahtarsız işlem",
            ],
            "correct": "A",
            "rationale": "Düşük seviye API yanlış kullanıma açıktır.",
        },
        {
            "q": "Anahtar rotasyonu ne zaman düşünülmelidir?",
            "opts": [
                "Sızıntı şüphesi, personel ayrılığı, politika süresi dolduğunda",
                "Her gün ECB değiştirmek için",
                "Yalnızca Sezar için",
                "Hiçbir zaman",
            ],
            "correct": "A",
            "rationale": "Operasyonel güvenliğin parçasıdır.",
        },
        {
            "q": "HSM veya KMS kullanımının özeti?",
            "opts": [
                "Anahtar materyalini uygulama belleğinden izole etmek",
                "Parolayı düz metin saklamak",
                "TLS’i kapatmak",
                "Frekans analizi",
            ],
            "correct": "A",
            "rationale": "Üretim anahtarları donanım/yönetimli depoda tutulur.",
        },
        {
            "q": "Zamanlama saldırılarına karşı `if (memcmp(a,b))` yerine ne önerilir?",
            "opts": [
                "Sabit zamanlı karşılaştırma (constant-time compare)",
                "Daha kısa anahtar",
                "ECB",
                "MD5",
            ],
            "correct": "A",
            "rationale": "MAC/tag karşılaştırmasında timing leak önlenmelidir.",
        },
        {
            "q": "Tehdit modeli olmadan «en güçlü AES» seçmek neden yetersiz?",
            "opts": [
                "Gerçek saldırı vektörü, veri ve anahtar yaşam döngüsü tanımsız kalır",
                "AES her zaman zayıftır",
                "Hash gereksizdir",
                "TLS gereksizdir",
            ],
            "correct": "A",
            "rationale": "Güvenlik ihtiyaca göre tasarlanır.",
        },
        {
            "q": "OpenSSL’de `MD5` veya `DES` ile yeni özellik geliştirmek?",
            "opts": [
                "Deprecated — modern alternatifler (AES-GCM, SHA-256, TLS 1.3)",
                "En iyi pratik",
                "Quantum dirençli",
                "OTP ile aynı",
            ],
            "correct": "A",
            "rationale": "Eski algoritmalar bilinen saldırılara açıktır.",
        },
    ],
}
