/** @typedef {'realistic'|'investigative'|'artistic'|'social'|'enterprising'|'conventional'} RiasecDim */

/** 48 maddelik meslek ilgi envanteri (Holland / RIASEC) */
export const CAREER_INTEREST_QUESTIONS = [
  { id: 'ci01', dimension: 'investigative', text: 'Balinalar ve diğer deniz canlıları hakkında araştırma yapmak.' },
  { id: 'ci02', dimension: 'conventional', text: 'Çalışanlara ait bilgileri ve kayıtları düzenli şekilde takip etmek.' },
  { id: 'ci03', dimension: 'conventional', text: 'Gelen ve giden ürünlerin kayıtlarını düzenli şekilde takip etmek.' },
  { id: 'ci04', dimension: 'investigative', text: 'Okyanus tabanını haritalandırmak.' },
  { id: 'ci05', dimension: 'realistic', text: 'Elektronik parçaları monte etmek.' },
  { id: 'ci06', dimension: 'enterprising', text: 'Bir oyuncak mağazasının işleyişini yönetmek.' },
  { id: 'ci07', dimension: 'investigative', text: 'İnsan vücudunun yapısı hakkında araştırma yapmak.' },
  { id: 'ci08', dimension: 'conventional', text: 'El terminaliyle ürün veya malzeme stoklarını saymak ve kaydetmek.' },
  { id: 'ci09', dimension: 'social', text: 'Bir kişiye egzersiz hareketlerini ve düzenli bir çalışma programını öğretmek.' },
  { id: 'ci10', dimension: 'realistic', text: 'Fabrikada taşlama makinesiyle üretim veya parça işleme yapmak.' },
  { id: 'ci11', dimension: 'enterprising', text: 'Bir güzellik salonu veya berber dükkânının işleyişini yönetmek.' },
  { id: 'ci12', dimension: 'realistic', text: 'Evlerde parke, fayans veya benzeri zemin kaplamalarını döşemek.' },
  { id: 'ci13', dimension: 'social', text: 'Bir sivil toplum kuruluşunda veya sosyal fayda odaklı bir kurumda gönüllü çalışmalar yapmak.' },
  { id: 'ci14', dimension: 'social', text: 'Alkol veya madde bağımlılığıyla mücadele eden kişilere destek olmak.' },
  { id: 'ci15', dimension: 'enterprising', text: 'Bir giyim mağazasının satış, ürün düzeni ve günlük işleyişini yönetmek.' },
  { id: 'ci16', dimension: 'enterprising', text: 'Büyük bir mağazada müşterilere ürün satışı yapmak.' },
  { id: 'ci17', dimension: 'conventional', text: 'Gönderimden önce ürün veya parçaların kalite kontrolünü yapmak.' },
  { id: 'ci18', dimension: 'conventional', text: 'Sayısal verileri hesaplamak, düzenlemek ve kayıt altına almak.' },
  { id: 'ci19', dimension: 'social', text: 'Aile içi sorunlar yaşayan kişilere destek olmak.' },
  { id: 'ci20', dimension: 'realistic', text: 'Fabrikada ürün parçalarını birleştirerek montaj yapmak.' },
  { id: 'ci21', dimension: 'artistic', text: 'Bir koroyu yönetmek ve müzik performansını yönlendirmek.' },
  { id: 'ci22', dimension: 'conventional', text: 'Müşterilerin para yatırma, çekme veya hesap işlemleri gibi banka işlemlerini yürütmek.' },
  { id: 'ci23', dimension: 'conventional', text: 'Bir ofiste çalışanların aylık maaş ve bordro ödemelerini hazırlamak.' },
  { id: 'ci24', dimension: 'enterprising', text: 'Büyük bir şirkette bir ekibin veya departmanın işleyişini yönetmek.' },
  { id: 'ci25', dimension: 'investigative', text: 'Canlılar, hücreler veya biyolojik süreçler üzerine araştırma yapmak.' },
  { id: 'ci26', dimension: 'social', text: 'Çocukların okuma becerisi kazanmasına yardımcı olmak.' },
  { id: 'ci27', dimension: 'artistic', text: 'Bir tiyatro oyununun sahne yönetimini ve oyuncu performanslarını yönlendirmek.' },
  { id: 'ci28', dimension: 'social', text: 'İnsanlara meslek seçimi, kariyer planı veya iş hayatı konusunda yol göstermek.' },
  { id: 'ci29', dimension: 'investigative', text: 'Bitkiler, hayvanlar veya canlı yaşamı hakkında araştırma yapmak.' },
  { id: 'ci30', dimension: 'artistic', text: 'Bir enstrüman çalmak veya müzik performansı sergilemek.' },
  { id: 'ci31', dimension: 'artistic', text: 'Tiyatro oyunları için sahne dekoru ve görsel ortam tasarlamak.' },
  { id: 'ci32', dimension: 'realistic', text: 'Duvar, zemin veya yapı yüzeylerinde tuğla ya da fayans döşeme işi yapmak.' },
  { id: 'ci33', dimension: 'realistic', text: 'Bozulan bir musluğu onarmak veya çalışır hale getirmek.' },
  { id: 'ci34', dimension: 'artistic', text: 'Dergiler için illüstrasyon, kapak veya görsel tasarım çalışmaları hazırlamak.' },
  { id: 'ci35', dimension: 'enterprising', text: 'Bir otelin günlük işleyişini, hizmet süreçlerini ve operasyonlarını yönetmek.' },
  { id: 'ci36', dimension: 'artistic', text: 'Şarkı sözü veya müzik bestesi oluşturmak.' },
  { id: 'ci37', dimension: 'investigative', text: 'Hayvanların davranışlarını, alışkanlıklarını ve çevreyle ilişkilerini araştırmak.' },
  { id: 'ci38', dimension: 'realistic', text: 'Açık denizdeki bir petrol sondaj platformunda teknik veya operasyonel görevlerde çalışmak.' },
  { id: 'ci39', dimension: 'enterprising', text: 'Müşterilere ev veya gayrimenkul satışı yapmak.' },
  { id: 'ci40', dimension: 'conventional', text: 'Hesap makinesi kullanarak sayısal işlemler yapmak.' },
  { id: 'ci41', dimension: 'enterprising', text: 'Restoran markası için girişimcilere bayilik satışı yapmak.' },
  { id: 'ci42', dimension: 'investigative', text: 'Hastalıkların tedavisi için yeni bir tıbbi yöntem veya sağlık uygulaması geliştirmek.' },
  { id: 'ci43', dimension: 'social', text: 'Yaşlı bireylerin günlük yaşam aktivitelerinde destek olmak.' },
  { id: 'ci44', dimension: 'artistic', text: 'Roman, hikâye veya tiyatro metni gibi yaratıcı yazılar yazmak.' },
  { id: 'ci45', dimension: 'realistic', text: 'Film veya televizyon yapımlarında tehlikeli ya da hareketli sahnelerde dublörlük yapmak.' },
  { id: 'ci46', dimension: 'investigative', text: 'Biyoloji laboratuvarında deney, gözlem veya araştırma çalışmalarına katılmak.' },
  { id: 'ci47', dimension: 'conventional', text: 'Bir bilgisayar programı kullanarak müşteri faturalarını hazırlamak.' },
  { id: 'ci48', dimension: 'social', text: 'Bir kampta çocukların etkinliklerini takip etmek, yönlendirmek ve güvenli şekilde katılmalarını sağlamak.' },
];
