export const BIG_FIVE_QUESTIONS = [
  { id: 'BF_001', text: 'Ortamlarda dikkat çeken ve enerjisiyle insanları canlandıran biri olurum.', dimension: 'extraversion', reverse: false },
  { id: 'BF_002', text: 'Başkaları için pek endişe duymam.', dimension: 'agreeableness', reverse: true },
  { id: 'BF_003', text: 'Kolayca strese girerim.', dimension: 'emotional_sensitivity', reverse: false },
  { id: 'BF_004', text: 'Her zaman hazırlıklıyımdır.', dimension: 'conscientiousness', reverse: false },
  { id: 'BF_005', text: 'Geniş bir kelime dağarcığına sahibim.', dimension: 'openness', reverse: false },

  { id: 'BF_006', text: 'Çok fazla konuşmam.', dimension: 'extraversion', reverse: true },
  { id: 'BF_007', text: 'İnsanları tanımaya ve anlamaya ilgi duyarım.', dimension: 'agreeableness', reverse: false },
  { id: 'BF_008', text: 'Çoğu zaman sakin ve rahatımdır.', dimension: 'emotional_sensitivity', reverse: true },
  { id: 'BF_009', text: 'Eşyalarımı düzenli bir yere koymak yerine genellikle ortalıkta bırakırım.', dimension: 'conscientiousness', reverse: true },
  { id: 'BF_010', text: 'Teorik veya soyut konuları kavramakta zorlanırım.', dimension: 'openness', reverse: true },

  { id: 'BF_011', text: 'İnsanların yanında kendimi rahat hissederim.', dimension: 'extraversion', reverse: false },
  { id: 'BF_012', text: 'İnsanlara kırıcı veya aşağılayıcı sözler söylerim.', dimension: 'agreeableness', reverse: true },
  { id: 'BF_013', text: 'Bir şeyler hakkında sık sık endişelenirim.', dimension: 'emotional_sensitivity', reverse: false },
  { id: 'BF_014', text: 'Detaylara dikkat ederim.', dimension: 'conscientiousness', reverse: false },
  { id: 'BF_015', text: 'Canlı ve güçlü bir hayal gücüm vardır.', dimension: 'openness', reverse: false },

  { id: 'BF_016', text: 'Genellikle geri planda kalırım.', dimension: 'extraversion', reverse: true },
  { id: 'BF_017', text: 'İnsanların ne hissettiğini önemser ve onlara empatiyle yaklaşırım.', dimension: 'agreeableness', reverse: false },
  { id: 'BF_018', text: 'Kendimi nadiren üzgün hissederim.', dimension: 'emotional_sensitivity', reverse: true },
  { id: 'BF_019', text: 'Bir işi yaparken düzensiz davranır ve işleri karmaşık hale getiririm.', dimension: 'conscientiousness', reverse: true },
  { id: 'BF_020', text: 'Teorik veya soyut konular ilgimi çekmez.', dimension: 'openness', reverse: true },

  { id: 'BF_021', text: 'Sohbetleri ben başlatırım.', dimension: 'extraversion', reverse: false },
  { id: 'BF_022', text: 'Başkalarının sorunlarıyla pek ilgilenmem.', dimension: 'agreeableness', reverse: true },
  { id: 'BF_023', text: 'Kolayca rahatsız olurum.', dimension: 'emotional_sensitivity', reverse: false },
  { id: 'BF_024', text: 'Yapmam gereken işleri ertelemeden tamamlarım.', dimension: 'conscientiousness', reverse: false },
  { id: 'BF_025', text: 'Yaratıcı ve güçlü fikirler ortaya koyarım.', dimension: 'openness', reverse: false },

  { id: 'BF_026', text: 'Sohbetlerde genellikle fazla konuşacak bir şey bulamam.', dimension: 'extraversion', reverse: true },
  { id: 'BF_027', text: 'Yumuşak kalpli biriyim.', dimension: 'agreeableness', reverse: false },
  { id: 'BF_028', text: 'Kolayca üzülürüm.', dimension: 'emotional_sensitivity', reverse: false },
  { id: 'BF_029', text: 'Eşyaları ait oldukları yere koymayı sık sık unuturum.', dimension: 'conscientiousness', reverse: true },
  { id: 'BF_030', text: 'Güçlü bir hayal gücüm yoktur.', dimension: 'openness', reverse: true },

  { id: 'BF_031', text: 'Kalabalık ortamlarda birçok farklı insanla konuşurum.', dimension: 'extraversion', reverse: false },
  { id: 'BF_032', text: 'İnsanları tanımaya veya onların ne yaptığıyla ilgilenmeye pek istekli olmam.', dimension: 'agreeableness', reverse: true },
  { id: 'BF_033', text: 'Ruh halim sık sık değişir.', dimension: 'emotional_sensitivity', reverse: false },
  { id: 'BF_034', text: 'Eşyaların, işlerin ve planların düzenli olmasından hoşlanırım.', dimension: 'conscientiousness', reverse: false },
  { id: 'BF_035', text: 'Yeni konuları veya durumları genellikle hızlı kavrarım.', dimension: 'openness', reverse: false },

  { id: 'BF_036', text: 'Dikkatleri üzerime çekmekten hoşlanmam.', dimension: 'extraversion', reverse: true },
  { id: 'BF_037', text: 'Başkaları için zaman ayırırım.', dimension: 'agreeableness', reverse: false },
  { id: 'BF_038', text: 'Sık sık ruh hali değişimleri yaşarım.', dimension: 'emotional_sensitivity', reverse: false },
  { id: 'BF_039', text: 'Sorumluluklarımdan kaçınırım.', dimension: 'conscientiousness', reverse: true },
  { id: 'BF_040', text: 'Kendimi ifade ederken bazen anlaşılması zor veya ileri düzey kelimeler kullanırım.', dimension: 'openness', reverse: false },

  { id: 'BF_041', text: 'İlgi odağı olmak beni rahatsız etmez.', dimension: 'extraversion', reverse: false },
  { id: 'BF_042', text: 'İnsanların ne hissettiğini kolayca anlayabilir ve onlarla duygusal bağ kurabilirim.', dimension: 'agreeableness', reverse: false },
  { id: 'BF_043', text: 'Kolayca sinirlenirim.', dimension: 'emotional_sensitivity', reverse: false },
  { id: 'BF_044', text: 'Bir programa göre hareket ederim.', dimension: 'conscientiousness', reverse: false },
  { id: 'BF_045', text: 'Bir şeyler üzerine düşünmeye zaman ayırırım.', dimension: 'openness', reverse: false },

  { id: 'BF_046', text: 'Tanımadığım insanların yanında sessiz olurum.', dimension: 'extraversion', reverse: true },
  { id: 'BF_047', text: 'İnsanların kendini rahat hissetmesini sağlarım.', dimension: 'agreeableness', reverse: false },
  { id: 'BF_048', text: 'Sık sık moralim bozulur veya içim daralır.', dimension: 'emotional_sensitivity', reverse: false },
  { id: 'BF_049', text: 'İşimde titiz davranırım.', dimension: 'conscientiousness', reverse: false },
  { id: 'BF_050', text: 'Aklıma sık sık yeni fikirler gelir.', dimension: 'openness', reverse: false },
];
